### ISSUE TITLE
Skipped installation of bin bin/create-idnamap for package mlocati/idna: file not found in package

### ISSUE THREAD

**Issue by Pascal76** [mlocati/idna#8]
- Upgrading mlocati/idna (1.0.1 => 1.1.0): Extracting archive
  - Upgrading illuminate/pagination (v9.51.0 => v10.0.3): Extracting archive
  0/10 [>---------------------------]   0%    Skipped installation of bin bin/create-idnamap for package mlocati/idna: file not found in package
Generating autoload files
    Skipped installation of bin bin/create-idnamap for package mlocati/idna: file not found in package

Is it ok ?

**Comment by mlocati** [comment]
I guess it isn't... I'll take a look at it asap
